###########################################
curlexe  = 'F:/z0bin/curl/bin/curl.exe'
sevenzip = 'C:/Program Files/7-Zip/7z.exe'
###########################################
base      = 'E:/4WWW/pub/'
emwinpath = base + 'wx-txt-emwin-ftp/'
dlpath    = emwinpath + 'dl'
dlzip     = emwinpath + 'dl/zip'
dlelse    = emwinpath + 'dl/else'
###########################################
DirATTACK    = emwinpath + '_ATTACK'
###########################################
DirNUCLEAR    = emwinpath + 'NUCLEAR'
###########################################
DirVOLCANO    = emwinpath + 'VOLCANO'
DirVOLCANOfv  = emwinpath + 'VOLCANO/FV'
DirVOLCANOwv  = emwinpath + 'VOLCANO/WV'
###########################################
DirTAF     = emwinpath + 'TAF'
DirOBSV    = emwinpath + 'OBSV'
DirMETAR   = emwinpath + 'OBSV/METAR'
DirSPECI   = emwinpath + 'OBSV/SPECI'
DirSYNOPm  = emwinpath + 'OBSV/SYNOPm'
DirSYNOPi  = emwinpath + 'OBSV/SYNOPi'
DirSYNOPn  = emwinpath + 'OBSV/SYNOPn'
DirRADREP  = emwinpath + 'OBSV/RADREP'
DirSEISMIC = emwinpath + 'OBSV/SEISMIC'
DirHYDRA   = emwinpath + 'OBSV/HYDRA'
DirBUOY    = emwinpath + 'OBSV/BUOY'
DirOCEAN   = emwinpath + 'OBSV/OCEAN'
###########################################
DirDATAMGT = emwinpath + 'DATAMGT'
DirFTM = emwinpath + 'FTM'
###########################################
DirCN     = emwinpath + 'CANADA'
DirCNcwhx = emwinpath + 'CANADA/CWHX'
DirCNcwnt = emwinpath + 'CANADA/CWNT'
DirCNcwqb = emwinpath + 'CANADA/CWQB'
DirCNcwto = emwinpath + 'CANADA/CWTO'
DirCNcwul = emwinpath + 'CANADA/CWUL'
DirCNcwvr = emwinpath + 'CANADA/CWVR'
DirCNcwwg = emwinpath + 'CANADA/CWWG'
DirCNcwxk = emwinpath + 'CANADA/CWXK'
DirCNcyqq = emwinpath + 'CANADA/CYQQ'
DirCNcytr = emwinpath + 'CANADA/CYTR'
DirCNcyzx = emwinpath + 'CANADA/CYZX'
###########################################
###########################################
DirCWHXhurFR = emwinpath + 'CWHXhurFR'
DirCWHXhurEN = emwinpath + 'CWHXhurEN'
###########################################
DirPHFO      = emwinpath + '1PHFO'
DirPHFOtcp   = emwinpath + '1PHFO/TCP'
DirPHFOtcm   = emwinpath + '1PHFO/TCM'
DirPHFOpws   = emwinpath + '1PHFO/PWS'
###########################################
DirJTWC           = emwinpath + '1JTWC'
DirPGTWsigwx      = emwinpath + '1JTWC/PGTW_SIGWX'
DirPGTWpos        = emwinpath + '1JTWC/PGTW_POS'
DirPGTWreason     = emwinpath + '1JTWC/PGTW_REASON'
DirPGTWformation  = emwinpath + '1JTWC/PGTW_FORMATION'
DirPGTWwarn       = emwinpath + '1JTWC/PGTW_WARN'
DirPHNCreason     = emwinpath + '1JTWC/PHNC_REASON'
DirPHNCformation  = emwinpath + '1JTWC/PHNC_FORMATION'
DirPHNCwarn       = emwinpath + '1JTWC/PHNC_WARN'
###########################################
DirElseHUR   = emwinpath + 'ElseHUR'
###########################################
DirKNHC            = emwinpath + '1KNHC'
DirKNHCtcpod       = emwinpath + '1KNHC/TCPOD'
DirKNHCnt          = emwinpath + '1KNHC/NT'
DirKNHCntTCP       = emwinpath + '1KNHC/NT/TCP'
DirKNHCntTCM       = emwinpath + '1KNHC/NT/TCM'
DirKNHCntTCD       = emwinpath + '1KNHC/NT/TCD'
DirKNHCntPWS       = emwinpath + '1KNHC/NT/PWS'
DirKNHCntTCU       = emwinpath + '1KNHC/NT/TCU'
DirKNHCntFCT       = emwinpath + '1KNHC/NT/FCT'
DirKNHCntFCTtwd    = emwinpath + '1KNHC/NT/FCT/TWD'
DirKNHCntFCTtwo    = emwinpath + '1KNHC/NT/FCT/TWO'
DirKNHCntFCTtws    = emwinpath + '1KNHC/NT/FCT/TWS'
DirKNHCntFCThsf    = emwinpath + '1KNHC/NT/FCT/HSF'
DirKNHCntFCToffn04 = emwinpath + '1KNHC/NT/FCT/OFF_N04'
DirKNHCntFCToffn05 = emwinpath + '1KNHC/NT/FCT/OFF_N05'
DirKNHCntFCToffn06 = emwinpath + '1KNHC/NT/FCT/OFF_N06'
DirKNHCntFCToffn20 = emwinpath + '1KNHC/NT/FCT/OFF_N20'
DirKNHCntFCToffn21 = emwinpath + '1KNHC/NT/FCT/OFF_N21'
DirKNHCntFCToffnt3 = emwinpath + '1KNHC/NT/FCT/OFF_NT3'
DirKNHCntFCToffnt4 = emwinpath + '1KNHC/NT/FCT/OFF_NT4'
DirKNHCntTWO       = emwinpath + '1KNHC/NT/TWO'
DirKNHCntUUU       = emwinpath + '1KNHC/NT/UUU'

DirKNHCntSATRAIN_0E = emwinpath + '1KNHC/NT/SATRAIN_0E'
DirKNHCntSATRAIN_1C = emwinpath + '1KNHC/NT/SATRAIN_1C'
DirKNHCntSATRAIN_2W = emwinpath + '1KNHC/NT/SATRAIN_2W'

DirKNHCpz          = emwinpath + '1KNHC/PZ'
DirKNHCpzTCP       = emwinpath + '1KNHC/PZ/TCP'
DirKNHCpzTCM       = emwinpath + '1KNHC/PZ/TCM'
DirKNHCpzTCD       = emwinpath + '1KNHC/PZ/TCD'
DirKNHCpzPWS       = emwinpath + '1KNHC/PZ/PWS'
DirKNHCpzTCU       = emwinpath + '1KNHC/PZ/TCU'
DirKNHCpzFCT       = emwinpath + '1KNHC/PZ/FCT'
DirKNHCpzFCTtwd    = emwinpath + '1KNHC/PZ/FCT/TWD'
DirKNHCpzFCTtwo    = emwinpath + '1KNHC/PZ/FCT/TWO'
DirKNHCpzFCTtws    = emwinpath + '1KNHC/PZ/FCT/TWS'
DirKNHCpzFCThsf    = emwinpath + '1KNHC/PZ/FCT/HSF'
DirKNHCpzFCToffpz7 = emwinpath + '1KNHC/PZ/FCT/OFF_PZ7'
DirKNHCpzFCToffpz8 = emwinpath + '1KNHC/PZ/FCT/OFF_PZ8'
DirKNHCpzTWO       = emwinpath + '1KNHC/PZ/TWO'
DirKNHCpzUUU       = emwinpath + '1KNHC/PZ/UUU'
DirKNHCtptpan      = emwinpath + '1KNHC/TPT_PAN'
DirKNHCelse        = emwinpath + '1KNHC/ELSE'
###########################################
###########################################
DirKWBN      = emwinpath + '1KWBN'
DirKWBNscs01 = emwinpath + '1KWBN/SCS_01'
DirKWBNscs02 = emwinpath + '1KWBN/SCS_02'
DirKWBNscs03 = emwinpath + '1KWBN/SCS_03'
DirKWBNscs04 = emwinpath + '1KWBN/SCS_04'
###########################################
DirKIWX = emwinpath + '0KIWX'
DirKLOT = emwinpath + '0KLOT'

DirKWBC = emwinpath + '1KWBC'
DirKMSR = emwinpath + '1KMSR'
DirKWNS = emwinpath + '1KWNS'

DirKWNH = emwinpath + '2KWNH'

DirKKCI = emwinpath + '2KKCI'
DirKMWI = emwinpath + '2KMWI'
DirKNAS = emwinpath + '2KNAS'
DirKNCF = emwinpath + '2KNCF'
DirKNEC = emwinpath + '2KNEC'
DirKNES = emwinpath + '2KNES'
DirKNWC = emwinpath + '2KNWC'
DirKPML = emwinpath + '2KPML'
DirKWAL = emwinpath + '2KWAL'
DirKWNB = emwinpath + '2KWNB'
DirKWNC = emwinpath + '2KWNC'
DirKWNE = emwinpath + '2KWNE'
DirKWNM = emwinpath + '2KWNM'
DirKWOH = emwinpath + '2KWOH'

DirKMSC = emwinpath + '8KMSC' # MARSHALL SPACEFLIGHT CENTRE
DirKWNJ = emwinpath + '8KWNJ' # JOHNSON  SPACEFLIGHT CENTRE

DirKWNP = emwinpath + '9KWNP' # SPACE WEATHER

###########################################
DirTSU      = emwinpath + 'TSUNAMI'
DirSPNTSU   = emwinpath + 'TSUNAMI/9_SPNTSU'
DirSPNTIB   = emwinpath + 'TSUNAMI/9_SPNTIB'
DirTSUVTEC  = emwinpath + 'TSUNAMI/8_VTEC'
###########################################
DirPAAQTSU = emwinpath + 'TSUNAMI/TSU_PAAQ'
DirPHEBTSU = emwinpath + 'TSUNAMI/TSU_PHEB'
DirPAAQTIB = emwinpath + 'TSUNAMI/TIB_PAAQ'
DirPHEBTIB = emwinpath + 'TSUNAMI/TIB_PHEB'
DirPAAQTST = emwinpath + 'TSUNAMI/TST_PAAQ'
DirPHEBTST = emwinpath + 'TSUNAMI/TST_PHEB'
###########################################
DirPNSWSH = emwinpath + 'PNSWSH'
DirPNS    = emwinpath + 'PNS'
DirPNSind = emwinpath + 'PNS/IND'
DirPNSiwx = emwinpath + 'PNS/IWX'
DirPNSlot = emwinpath + 'PNS/LOT'
###########################################
DirADA = emwinpath + 'ADA'
DirADAcrh = emwinpath + 'ADA/CRH'
DirADAerh = emwinpath + 'ADA/ERH'
DirADAind = emwinpath + 'ADA/IND'
DirADAiwx = emwinpath + 'ADA/IWX'
DirADAlot = emwinpath + 'ADA/LOT'
DirADAmsr = emwinpath + 'ADA/MSR'
DirADAnes = emwinpath + 'ADA/NES'
DirADAsrh = emwinpath + 'ADA/SRH'
DirADAwno = emwinpath + 'ADA/WNO'
DirADAwns = emwinpath + 'ADA/WNS'
###########################################
DirADM = emwinpath + 'ADM'
DirADMcrh = emwinpath + 'ADM/CRH'
DirADMerh = emwinpath + 'ADM/ERH'
DirADMind = emwinpath + 'ADM/IND'
DirADMiwx = emwinpath + 'ADM/IWX'
DirADMlot = emwinpath + 'ADM/LOT'
DirADMmsr = emwinpath + 'ADM/MSR'
DirADMnes = emwinpath + 'ADM/NES'
DirADMsrh = emwinpath + 'ADM/SRH'
DirADMwno = emwinpath + 'ADM/WNO'
DirADMwns = emwinpath + 'ADM/WNS'
###########################################
DirMPD = emwinpath + 'MPD'
DirSCC = emwinpath + 'SCC'
###########################################
DirKIWXfld = emwinpath + '0KIWX/FLD'
DirKIWXeee = emwinpath + '0KIWX/FLD/EEE'
DirKIWXffw = emwinpath + '0KIWX/FLD/FFW'
DirKIWXffa = emwinpath + '0KIWX/FLD/FFA'
DirKIWXffs = emwinpath + '0KIWX/FLD/FFS'
DirKIWXflw = emwinpath + '0KIWX/FLD/FLW'
DirKIWXfls = emwinpath + '0KIWX/FLD/FLS'
###########################################
DirKLOTfld = emwinpath + '0KLOT/FLD'
DirKLOTeee = emwinpath + '0KLOT/FLD/EEE'
DirKLOTffw = emwinpath + '0KLOT/FLD/FFW'
DirKLOTffa = emwinpath + '0KLOT/FLD/FFA'
DirKLOTffs = emwinpath + '0KLOT/FLD/FFS'
DirKLOTflw = emwinpath + '0KLOT/FLD/FLW'
DirKLOTfls = emwinpath + '0KLOT/FLD/FLS'
###########################################
DirLSR     = emwinpath + 'LSR'
DirLSRkiwx = emwinpath + 'LSR/KIWX'
DirLSRklot = emwinpath + 'LSR/KLOT'
###########################################
DirSVR     = emwinpath + 'SVR'
DirSVRkiwx = emwinpath + 'SVR/KIWX'
DirSVRklot = emwinpath + 'SVR/KLOT'
###########################################
DirKIWXafd = emwinpath + '0KIWX/AFD'
DirKIWXafm = emwinpath + '0KIWX/AFM'
DirKIWXcfw = emwinpath + '0KIWX/CFW'
DirKIWXcli = emwinpath + '0KIWX/CLI'
DirKIWXfwf = emwinpath + '0KIWX/FWF'
DirKIWXhwo = emwinpath + '0KIWX/HWO'
DirKIWXmws = emwinpath + '0KIWX/MWS'
DirKIWXmww = emwinpath + '0KIWX/MWW'
DirKIWXnpw = emwinpath + '0KIWX/NPW'
DirKIWXnsh = emwinpath + '0KIWX/NSH'
DirKIWXomr = emwinpath + '0KIWX/OMR'
DirKIWXrtp = emwinpath + '0KIWX/RTP'
DirKIWXrva = emwinpath + '0KIWX/RVA'
DirKIWXrvd = emwinpath + '0KIWX/RVD'
DirKIWXrvs = emwinpath + '0KIWX/RVS'
DirKIWXrwr = emwinpath + '0KIWX/RWR'
DirKIWXpfm = emwinpath + '0KIWX/PFM'
DirKIWXsmw = emwinpath + '0KIWX/SMW'
DirKIWXsrf = emwinpath + '0KIWX/SRF'
DirKIWXwcn = emwinpath + '0KIWX/WCN'
DirKIWXwsw = emwinpath + '0KIWX/WSW'
DirKIWXzfp = emwinpath + '0KIWX/ZFP'
###########################################
DirKLOTafd = emwinpath + '0KLOT/AFD'
DirKLOTafm = emwinpath + '0KLOT/AFM'
DirKLOTcfw = emwinpath + '0KLOT/CFW'
DirKLOTcli = emwinpath + '0KLOT/CLI'
DirKLOTfld = emwinpath + '0KLOT/FLD'
DirKLOTfwf = emwinpath + '0KLOT/FWF'
DirKLOThwo = emwinpath + '0KLOT/HWO'
DirKLOTmws = emwinpath + '0KLOT/MWS'
DirKLOTmww = emwinpath + '0KLOT/MWW'
DirKLOTnpw = emwinpath + '0KLOT/NPW'
DirKLOTnsh = emwinpath + '0KLOT/NSH'
DirKLOTomr = emwinpath + '0KLOT/OMR'
DirKLOTpfm = emwinpath + '0KLOT/PFM'
DirKLOTrtp = emwinpath + '0KLOT/RTP'
DirKLOTrva = emwinpath + '0KLOT/RVA'
DirKLOTrvd = emwinpath + '0KLOT/RVD'
DirKLOTrwr = emwinpath + '0KLOT/RWR'
DirKLOTsmw = emwinpath + '0KLOT/SMW'
DirKLOTsrf = emwinpath + '0KLOT/SRF'
DirKLOTwcn = emwinpath + '0KLOT/WCN'
DirKLOTwsw = emwinpath + '0KLOT/WSW'
DirKLOTzfp = emwinpath + '0KLOT/ZFP'
###########################################
DirKWNSmcd     = emwinpath + '1KWNS/MCD'
DirKWNSsaw     = emwinpath + '1KWNS/SAW'
DirKWNSsel     = emwinpath + '1KWNS/SEL'
DirKWNSsta     = emwinpath + '1KWNS/STA'
DirKWNSswody1  = emwinpath + '1KWNS/SWODY1'
DirKWNSswody2  = emwinpath + '1KWNS/SWODY2'
DirKWNSswody3  = emwinpath + '1KWNS/SWODY3'
DirKWNSswody48 = emwinpath + '1KWNS/SWODY48'
DirKWNSwou     = emwinpath + '1KWNS/WOU'
DirKWNSwwa     = emwinpath + '1KWNS/WWA'
DirKWNSwwp     = emwinpath + '1KWNS/WWP'
DirKWNSfwddy1  = emwinpath + '1KWNS/FWD_DY1'
DirKWNSfwddy2  = emwinpath + '1KWNS/FWD_DY2'
DirKWNSfwdd38  = emwinpath + '1KWNS/FWD_D38'
DirKWNSpfwf38  = emwinpath + '1KWNS/PFW_F38'
DirKWNSptsd48  = emwinpath + '1KWNS/PTS_D48'
###########################################
DirNWEM     = emwinpath + 'NWEM'
DirNWEMelse = emwinpath + 'NWEM/ELSE'
###########################################
DirKWBCcodsrp     = emwinpath + '1KWBC/COD_SRP'
DirKWBCcodsus     = emwinpath + '1KWBC/COD_SUS'
DirKWBChsfat1     = emwinpath + '1KWBC/HSF_AT1'
DirKWBChsfep1     = emwinpath + '1KWBC/HSF_EP1'
DirKWBChsfepi     = emwinpath + '1KWBC/HSF_EPI'
DirKWBCoffn31     = emwinpath + '1KWBC/OFF_N31'
DirKWBCoffn32     = emwinpath + '1KWBC/OFF_N32'
DirKWBCoffn35     = emwinpath + '1KWBC/OFF_N35'
DirKWBCoffn36     = emwinpath + '1KWBC/OFF_N36'
DirKWBCoffnt1     = emwinpath + '1KWBC/OFF_NT1'
DirKWBCoffnt2     = emwinpath + '1KWBC/OFF_NT2'
DirKWBCoffpz5     = emwinpath + '1KWBC/OFF_PZ5'
DirKWBCoffpz6     = emwinpath + '1KWBC/OFF_PZ6'
DirKWBCpmdcaa     = emwinpath + '1KWBC/PMD_CAA'
DirKWBCpmdepd     = emwinpath + '1KWBC/PMD_EPD'
DirKWBCpmdmrd     = emwinpath + '1KWBC/PMD_MRD'
DirKWBCpmdspd     = emwinpath + '1KWBC/PMD_SPD'
DirKWBCqpferd     = emwinpath + '1KWBC/QPF_ERD'
DirKWBCtptcan     = emwinpath + '1KWBC/TPT_CAN'
DirKWBCtptcrn     = emwinpath + '1KWBC/TPT_CRN'
DirKWBCtptern     = emwinpath + '1KWBC/TPT_ERN'
DirKWBCtptint     = emwinpath + '1KWBC/TPT_INT'
DirKWBCtptlat     = emwinpath + '1KWBC/TPT_LAT'
DirKWBCtptnam     = emwinpath + '1KWBC/TPT_NAM'
DirKWBCtptwrn     = emwinpath + '1KWBC/TPT_WRN'
DirKWBCuuu        = emwinpath + '1KWBC/UUU'
DirKWBCuvi        = emwinpath + '1KWBC/UVI'
###########################################
DirKWBCwintem        = emwinpath + '1KWBC/WINTEM'
DirKWBCwintem11A     = emwinpath + '1KWBC/WINTEM/WIN_11A'
DirKWBCwintem12A     = emwinpath + '1KWBC/WINTEM/WIN_12A'
DirKWBCwintem13A     = emwinpath + '1KWBC/WINTEM/WIN_13A'
DirKWBCwintem14A     = emwinpath + '1KWBC/WINTEM/WIN_14A'
DirKWBCwintem21A     = emwinpath + '1KWBC/WINTEM/WIN_21A'
DirKWBCwintem22A     = emwinpath + '1KWBC/WINTEM/WIN_22A'
DirKWBCwintem23A     = emwinpath + '1KWBC/WINTEM/WIN_23A'
DirKWBCwintem24A     = emwinpath + '1KWBC/WINTEM/WIN_24A'
DirKWBCwintem25A     = emwinpath + '1KWBC/WINTEM/WIN_25A'
DirKWBCwintem26A     = emwinpath + '1KWBC/WINTEM/WIN_26A'
DirKWBCwintem27A     = emwinpath + '1KWBC/WINTEM/WIN_27A'
DirKWBCwintem28A     = emwinpath + '1KWBC/WINTEM/WIN_28A'
DirKWBCwintemA11     = emwinpath + '1KWBC/WINTEM/WIN_A11'
DirKWBCwintemA12     = emwinpath + '1KWBC/WINTEM/WIN_A12'
DirKWBCwintemA21     = emwinpath + '1KWBC/WINTEM/WIN_A21'
DirKWBCwintemA22     = emwinpath + '1KWBC/WINTEM/WIN_A22'
DirKWBCwintemT11     = emwinpath + '1KWBC/WINTEM/WIN_T11'
DirKWBCwintemT12     = emwinpath + '1KWBC/WINTEM/WIN_T12'
DirKWBCwintemT13     = emwinpath + '1KWBC/WINTEM/WIN_T13'
DirKWBCwintemT14     = emwinpath + '1KWBC/WINTEM/WIN_T14'
DirKWBCwintemT15     = emwinpath + '1KWBC/WINTEM/WIN_T15'
DirKWBCwintemT16     = emwinpath + '1KWBC/WINTEM/WIN_T16'
DirKWBCwintemT17     = emwinpath + '1KWBC/WINTEM/WIN_T17'
DirKWBCwintemT18     = emwinpath + '1KWBC/WINTEM/WIN_T18'
DirKWBCwintemT21     = emwinpath + '1KWBC/WINTEM/WIN_T21'
DirKWBCwintemT22     = emwinpath + '1KWBC/WINTEM/WIN_T22'
DirKWBCwintemT23     = emwinpath + '1KWBC/WINTEM/WIN_T23'
DirKWBCwintemT24     = emwinpath + '1KWBC/WINTEM/WIN_T24'
DirKWBCwintemT25     = emwinpath + '1KWBC/WINTEM/WIN_T25'
DirKWBCwintemT26     = emwinpath + '1KWBC/WINTEM/WIN_T26'
DirKWBCwintemT27     = emwinpath + '1KWBC/WINTEM/WIN_T27'
DirKWBCwintemT28     = emwinpath + '1KWBC/WINTEM/WIN_T28'
DirKWBCwintemT29     = emwinpath + '1KWBC/WINTEM/WIN_T29'
DirKWBCwintemT30     = emwinpath + '1KWBC/WINTEM/WIN_T30'
DirKWBCwintemT31     = emwinpath + '1KWBC/WINTEM/WIN_T31'
DirKWBCwintemT32     = emwinpath + '1KWBC/WINTEM/WIN_T32'
##########################################
DirKMSRffh    = emwinpath + '1KMSR/FFH'
DirKMSRffhapx = emwinpath + '1KMSR/FFH/FFH_APX'
DirKMSRffharx = emwinpath + '1KMSR/FFH/FFH_ARX'
DirKMSRffhdmx = emwinpath + '1KMSR/FFH/FFH_DMX'
DirKMSRffhfgf = emwinpath + '1KMSR/FFH/FFH_FGF'
DirKMSRffhilx = emwinpath + '1KMSR/FFH/FFH_ILX'
DirKMSRffhlot = emwinpath + '1KMSR/FFH/FFH_LOT'
DirKMSRffhlsx = emwinpath + '1KMSR/FFH/FFH_LSX'
DirKMSRffhmkx = emwinpath + '1KMSR/FFH/FFH_MKX'
DirKMSRffhmpx = emwinpath + '1KMSR/FFH/FFH_MPX'

DirKMSRqpsmsr = emwinpath + '1KMSR/QPS_MSR'
DirKMSRrvf    = emwinpath + '1KMSR/RVF'
DirKMSRrvfcal = emwinpath + '1KMSR/RVF/RVF_CAL'
DirKMSRrvfchp = emwinpath + '1KMSR/RVF/RVF_CHP'
DirKMSRrvfciw = emwinpath + '1KMSR/RVF/RVF_CIW'
DirKMSRrvfdes = emwinpath + '1KMSR/RVF/RVF_DES'
DirKMSRrvfews = emwinpath + '1KMSR/RVF/RVF_EWS'
DirKMSRrvfgnd = emwinpath + '1KMSR/RVF/RVF_GND'
DirKMSRrvfilo = emwinpath + '1KMSR/RVF/RVF_ILO'
DirKMSRrvfkbm = emwinpath + '1KMSR/RVF/RVF_KBM'
DirKMSRrvfkdf = emwinpath + '1KMSR/RVF/RVF_KDF'
DirKMSRrvfksj = emwinpath + '1KMSR/RVF/RVF_KSJ'
DirKMSRrvfm10 = emwinpath + '1KMSR/RVF/RVF_M10'
DirKMSRrvfm19 = emwinpath + '1KMSR/RVF/RVF_M19'
DirKMSRrvfmec = emwinpath + '1KMSR/RVF/RVF_MEC'
DirKMSRrvfmin = emwinpath + '1KMSR/RVF/RVF_MIN'
DirKMSRrvfmis = emwinpath + '1KMSR/RVF/RVF_MIS'
DirKMSRrvfmwm = emwinpath + '1KMSR/RVF/RVF_MWM'
DirKMSRrvfnlm = emwinpath + '1KMSR/RVF/RVF_NLM'
DirKMSRrvfrck = emwinpath + '1KMSR/RVF/RVF_RCK'
DirKMSRrvfrdw = emwinpath + '1KMSR/RVF/RVF_RDW'
DirKMSRrvfred = emwinpath + '1KMSR/RVF/RVF_RED'
DirKMSRrvfsms = emwinpath + '1KMSR/RVF/RVF_SMS'
DirKMSRrvfsmw = emwinpath + '1KMSR/RVF/RVF_SMW'
DirKMSRrvfssl = emwinpath + '1KMSR/RVF/RVF_SSL'
DirKMSRrvftia = emwinpath + '1KMSR/RVF/RVF_TIA'
DirKMSRrvftmo = emwinpath + '1KMSR/RVF/RVF_TMO'
DirKMSRrvfupm = emwinpath + '1KMSR/RVF/RVF_UPM'
DirKMSRrvfwis = emwinpath + '1KMSR/RVF/RVF_WIS'
##########################################
DirKWNHpmdakk = emwinpath + '2KWNH/PMD_AKK'
DirKWNHpmdhii = emwinpath + '2KWNH/PMD_HII'
DirKWNHpmdhmd = emwinpath + '2KWNH/PMD_HMD'
DirKWNHprbehh = emwinpath + '2KWNH/PRB_EHH'
DirKWNHprbehi = emwinpath + '2KWNH/PRB_EHI'
DirKWNHprbehl = emwinpath + '2KWNH/PRB_EHL'
DirKWNHprbwhh = emwinpath + '2KWNH/PRB_WHH'
DirKWNHprbwhi = emwinpath + '2KWNH/PRB_WHI'
DirKWNHprbwhl = emwinpath + '2KWNH/PRB_WHL'
##########################################
